name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:
  # schedule:
   # - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        
    - name: Fetch all tags and branches (RobustToolbox)
      run: |
        cd RobustToolbox
        git fetch --all --tags

    #- name: Debug tags for RobustToolbox
    #  run: |
    #    cd RobustToolbox
    #    git tag
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x

    #- name: Get Engine Tag
    #  run: |
    #    cd RobustToolbox
    #    git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --hybrid-acz --platform linux-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    #- name: Publish version
    #  uses: actions/forgejo-release@v2.6.0
    #  with:
    #    direction: upload
    #    url: https://git.avali.one
    #    repo: mackandelius/space-station-14
    #    token: ${{ secrets.PUBLISH_TOKEN }}
    #    tag: ${{ github.ref_name }}
    #    release-dir: release

    - name: Verify files
      run: ls ./release

      
    - name: Upload client package
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        CLIENTENDPOINT: ${{ secrets.CLIENTENDPOINT }}
      run: curl --user mackandelius:"$PACKAGE_TOKEN" --upload-file ./release/SS14.Client.zip "$CLIENTENDPOINT"

    - name: Upload ARM64 server package
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        SERVERENDPOINTARM: ${{ secrets.SERVERENDPOINTARM }}
      run: curl --user mackandelius:"$PACKAGE_TOKEN" --upload-file ./release/SS14.Server_linux-arm64.zip "$SERVERENDPOINTARM"
      
    - name: Upload x86 server package
      env:
        PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        SERVERENDPOINTX64: ${{ secrets.SERVERENDPOINTX64 }}
      run: curl --user mackandelius:"$PACKAGE_TOKEN" --upload-file ./release/SS14.Server_linux-x64.zip "$SERVERENDPOINTX64"
